"""Build the Mariner 9 test image used by the error-correcting-codes notebook.

Source: NASA/JPL image PIA02999, "Mariner 9 views Olympus Mons standing above the
Martian Dust Storm" (1971), public domain, from the NASA Image and Video Library:
    https://images-assets.nasa.gov/image/PIA02999/PIA02999~medium.jpg

Mariner 9 sent each pixel as one of 64 grey levels (6 bits), protected by the
first-order Reed-Muller code RM(1,5). To match, this script crops a 640 x 640
region around the volcano, downsamples it to 128 x 128, and quantizes it to the
values 0..63. The black dots are the camera's reference marks, part of the original
frame.

The pixels are written, one byte per pixel and base64-encoded, into the block
between the BEGIN/END markers in the notebook, so the notebook needs no data files.

Usage (maintainers only; needs network access, numpy and Pillow):
    uv run --group data python data/prepare_mariner9.py
"""
import base64
import io
import sys
import textwrap
import urllib.request
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK = ROOT / "notebooks" / "07-linear-error-correcting-codes.py"
CACHE = ROOT / "data" / ".cache" / "PIA02999~medium.jpg"
URL = "https://images-assets.nasa.gov/image/PIA02999/PIA02999~medium.jpg"
BOX = (20, 300, 660, 940)        # left, top, right, bottom in the 1280 x 1055 medium image
SIZE = 128
LEVELS = 64                      # 6 bits per pixel, as on Mariner 9
BEGIN, END = "    # BEGIN MARINER DATA", "    # END MARINER DATA"


def fetch():
    if not CACHE.exists():
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(URL) as resp:
            CACHE.write_bytes(resp.read())
    return Image.open(io.BytesIO(CACHE.read_bytes())).convert("L")


def pixels(img):
    small = img.crop(BOX).resize((SIZE, SIZE), Image.LANCZOS)
    v = np.asarray(small, dtype=float) / 255 * (LEVELS - 1)
    return np.clip(np.round(v), 0, LEVELS - 1).astype(np.uint8)


def literal(q):
    b64 = base64.b64encode(q.tobytes()).decode("ascii")
    lines = textwrap.wrap(b64, 92)
    out = [BEGIN + " (generated by data/prepare_mariner9.py; NASA/JPL PIA02999)",
           f"    image_shape = ({SIZE}, {SIZE})",
           "    image_b64 = ("]
    out += [f'        "{line}"' for line in lines]
    out += ["    )", END]
    return "\n".join(out)


def main():
    q = pixels(fetch())
    assert q.shape == (SIZE, SIZE) and q.max() < LEVELS
    text = NOTEBOOK.read_text()
    start, stop = text.index(BEGIN), text.index(END) + len(END)
    NOTEBOOK.write_text(text[:start] + literal(q) + text[stop:])
    print(f"wrote {SIZE}x{SIZE} Mariner 9 image ({q.size} pixels, levels {q.min()}..{q.max()}) "
          f"into {NOTEBOOK.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
